# Generated by Django 2.2 on 2020-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='msg2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
