# Generated by Django 2.2 on 2020-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='msg',
            field=models.TextField(),
        ),
    ]
