# Generated by Django 2.2 on 2020-02-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='flag',
            field=models.CharField(blank=True, choices=[('racist', 'racist'), ('abbusing', 'abbusing')], max_length=20, null=True),
        ),
    ]
