# Generated by Django 2.2 on 2020-02-10 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postcomment_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cr_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 19, 4, 56, 76550, tzinfo=utc)),
        ),
    ]
